CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetUsers" (
    "Id" text NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");

CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");

CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");

CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");

CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260703154559_Initial', '10.0.9');

COMMIT;

START TRANSACTION;
ALTER TABLE "AspNetUsers" ADD "FullName" text;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260703160447_AddAuth', '10.0.9');

COMMIT;

START TRANSACTION;
ALTER TABLE "AspNetUsers" ADD "Avatar" text;

ALTER TABLE "AspNetUsers" ADD "Banner" text;

ALTER TABLE "AspNetUsers" ADD "Bio_FirstLine" text;

ALTER TABLE "AspNetUsers" ADD "Bio_SecondLine" text;

ALTER TABLE "AspNetUsers" ADD "Followers" integer;

ALTER TABLE "AspNetUsers" ADD "Followings" integer;

ALTER TABLE "AspNetUsers" ADD "Technologies" text[];

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260704165648_addUserData', '10.0.9');

COMMIT;

START TRANSACTION;
CREATE TABLE "Post" (
    "Id" uuid NOT NULL,
    "Created" timestamp with time zone NOT NULL,
    "Content" text,
    "Attachments" text[] NOT NULL,
    "Likes" integer NOT NULL,
    "Comments" integer NOT NULL,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_Post" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Post_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Post_UserId" ON "Post" ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260705073637_AddPosts', '10.0.9');

COMMIT;

START TRANSACTION;
ALTER TABLE "Post" RENAME COLUMN "Likes" TO "LikesCount";

ALTER TABLE "Post" RENAME COLUMN "Comments" TO "CommentsCount";

CREATE TABLE "Comment" (
    "Id" uuid NOT NULL,
    "Content" text NOT NULL,
    "Created" timestamp with time zone NOT NULL,
    "PostId" uuid NOT NULL,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_Comment" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Comment_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Comment_Post_PostId" FOREIGN KEY ("PostId") REFERENCES "Post" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Comment_PostId" ON "Comment" ("PostId");

CREATE INDEX "IX_Comment_UserId" ON "Comment" ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260705151405_AddComments', '10.0.9');

COMMIT;

START TRANSACTION;
ALTER TABLE "AspNetUsers" ADD "ConnectedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

ALTER TABLE "AspNetUsers" ADD "IsActive" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "AspNetUsers" ADD "Room" text NOT NULL DEFAULT '';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260708090031_AddOnline', '10.0.9');

COMMIT;

START TRANSACTION;
CREATE TABLE "Chat" (
    "Id" uuid NOT NULL,
    "Title" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Chat" PRIMARY KEY ("Id")
);

CREATE TABLE "ChatParticipant" (
    "ChatId" uuid NOT NULL,
    "UserId" text NOT NULL,
    "JoinedAt" timestamp with time zone NOT NULL,
    "LastReadAt" timestamp with time zone,
    CONSTRAINT "PK_ChatParticipant" PRIMARY KEY ("ChatId", "UserId"),
    CONSTRAINT "FK_ChatParticipant_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ChatParticipant_Chat_ChatId" FOREIGN KEY ("ChatId") REFERENCES "Chat" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Message" (
    "Id" uuid NOT NULL,
    "ChatId" uuid NOT NULL,
    "SenderId" text NOT NULL,
    "Content" text NOT NULL,
    "Attachments" text[] NOT NULL,
    "SentAt" timestamp with time zone NOT NULL,
    "IsRead" boolean NOT NULL,
    CONSTRAINT "PK_Message" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Message_AspNetUsers_SenderId" FOREIGN KEY ("SenderId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Message_Chat_ChatId" FOREIGN KEY ("ChatId") REFERENCES "Chat" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_ChatParticipant_UserId" ON "ChatParticipant" ("UserId");

CREATE INDEX "IX_Message_ChatId" ON "Message" ("ChatId");

CREATE INDEX "IX_Message_SenderId" ON "Message" ("SenderId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260808131012_AddChatModels', '10.0.9');

COMMIT;

START TRANSACTION;
CREATE TABLE "PostLikes" (
    "Id" uuid NOT NULL,
    "PostId" uuid NOT NULL,
    "UserId" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_PostLikes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PostLikes_Post_PostId" FOREIGN KEY ("PostId") REFERENCES "Post" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_PostLikes_PostId" ON "PostLikes" ("PostId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260827142024_addLikes', '10.0.9');

COMMIT;

START TRANSACTION;
ALTER TABLE "Message" ADD "ReplyToId" uuid;

CREATE INDEX "IX_Message_ReplyToId" ON "Message" ("ReplyToId");

ALTER TABLE "Message" ADD CONSTRAINT "FK_Message_Message_ReplyToId" FOREIGN KEY ("ReplyToId") REFERENCES "Message" ("Id");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260827161423_addReplies', '10.0.9');

COMMIT;

START TRANSACTION;
ALTER TABLE "AspNetUsers" ALTER COLUMN "Room" DROP NOT NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260902164431_changeUser', '10.0.9');

COMMIT;

START TRANSACTION;
ALTER TABLE "Post" ADD "RepostOfPostId" uuid;

ALTER TABLE "Post" ADD "RepostsCount" integer NOT NULL DEFAULT 0;

CREATE INDEX "IX_Post_RepostOfPostId" ON "Post" ("RepostOfPostId");

ALTER TABLE "Post" ADD CONSTRAINT "FK_Post_Post_RepostOfPostId" FOREIGN KEY ("RepostOfPostId") REFERENCES "Post" ("Id");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260908161008_AddReposts', '10.0.9');

COMMIT;

